# frozen_string_literal: true

class Axeng < Formula
  desc "Engineering Manager Accelerator — AI chief of staff for GitHub, Linear, calendar, and team"
  homepage "https://github.com/ruimachado-orbit/axeng"
  license "GPL-3.0"
  url "https://github.com/ruimachado-orbit/axeng.git", tag: "v2.1.1"
  version "2.1.1"
  head "https://github.com/ruimachado-orbit/axeng.git", branch: "main"

  depends_on "node"
  depends_on "python@3.12"
  depends_on "gh"

  def install
    # Install the entire repo to libexec
    libexec.install Dir["*"]

    # Create a Python virtual environment
    venv = libexec/"venv"
    system Formula["python@3.12"].opt_bin/"python3.12", "-m", "venv", venv

    # Install Python dependencies in the virtualenv
    system venv/"bin/pip", "install", "--upgrade", "pip"
    system venv/"bin/pip", "install", "-r", libexec/"requirements.txt"

    # Install Node.js dependencies for UI
    cd libexec/"ui/nextjs" do
      system "npm", "install"
    end

    # Create wrapper scripts
    (bin/"axeng").write <<~EOS
      #!/bin/bash
      export AXENG_HOME="#{var}/axeng"
      export PYTHONPATH="#{libexec}/src:$PYTHONPATH"
      export PATH="#{libexec}/ui/nextjs/node_modules/.bin:$PATH"

      # Ensure config directory exists
      mkdir -p "$AXENG_HOME"

      # If no arguments, show help
      if [ $# -eq 0 ]; then
        exec "#{venv}/bin/python3" "#{libexec}/bin/axeng-cli" --help
      fi

      # Run CLI with all arguments
      exec "#{venv}/bin/python3" "#{libexec}/bin/axeng-cli" "$@"
    EOS

    # Create axeng-dev wrapper (starts Next.js UI)
    (bin/"axeng-dev").write <<~EOS
      #!/bin/bash
      cd "#{libexec}/ui/nextjs"
      export AXENG_HOME="#{var}/axeng"
      export PYTHONPATH="#{libexec}/src:$PYTHONPATH"

      echo "🚀 Starting Axeng Next.js UI..."

      # Start API backend in background
      "#{venv}/bin/python3" api_server.py > /tmp/axeng-api.log 2>&1 &
      API_PID=$!

      # Start Next.js
      npm run dev

      # Kill API on exit
      kill $API_PID 2>/dev/null || true
    EOS

    chmod 0755, bin/"axeng"
    chmod 0755, bin/"axeng-dev"

    # Create var directory for user config
    (var/"axeng").mkpath

    # Copy example configs if they don't exist
    unless (var/"axeng/.env").exist?
      cp libexec/".env.example", var/"axeng/.env.example"
    end

    unless (var/"axeng/config.yaml").exist?
      cp libexec/"config/config.yaml.example", var/"axeng/config.yaml.example"
    end
  end

  def post_install
    ohai "🎉 Axeng v2.1.1 - Engineering Manager Command Center!"
    puts ""
    puts "🆕 What's new in v2.1.1:"
    puts "  🔍 Real-time progress indicators"
    puts "  📊 PR health analysis (axeng pr-health)"
    puts "  💡 Smart query suggestions in chat"
    puts "  📈 Linear project health analytics"
    puts "  🐛 Bug fixes (JSON import, PR timeout)"
    puts ""
    puts "Quick start:"
    puts "  axeng configure    # Interactive wizard (2 min)"
    puts "  axeng chat         # Chat with smart suggestions"
    puts "  axeng pr-health    # Check PR pipeline"
    puts "  axeng --help       # See all commands"
    puts ""
    puts "Daily operations:"
    puts "  axeng ooo          # Who's out today"
    puts "  axeng issues       # My Linear issues"
    puts "  axeng prs          # My GitHub PRs"
    puts "  axeng standup      # Daily standup brief"
    puts ""
    puts "EM workflows:"
    puts "  axeng prep [name]  # 1:1 meeting prep"
    puts "  axeng team         # Team management"
    puts "  axeng offboard [user] --dry-run  # Safe offboarding"
    puts ""
    puts "Time savings: 30-45 minutes per day!"
    puts ""
    puts "Configuration: #{var}/axeng/.env"
    puts "Release notes: https://github.com/ruimachado-orbit/axeng/releases/tag/v2.1.1"
  end

  def caveats
    <<~CAVEATS
      Axeng v2.1.1 - Engineering Manager Command Center

      🆕 New in v2.1.1:
        🔍 Real-time progress indicators
        📊 PR health analysis (axeng pr-health)
        💡 Smart query suggestions
        📈 Project health analytics

      Quick start:
        axeng configure    # Interactive wizard
        axeng chat         # Chat with smart suggestions
        axeng pr-health    # Check PR pipeline
        axeng ooo          # Who's OOO today

      All commands:
        axeng --help       # See full list

      Configuration:
        #{var}/axeng/.env          # Auto-generated by wizard
        #{var}/axeng/config.yaml   # Team/project settings

      Required API keys (get via interactive wizard):
        LINEAR_API_KEY      — linear.app/settings/api
        GITHUB_TOKEN        — github.com/settings/tokens
        LLM provider key    — OpenCode/Anthropic/OpenAI

      Release notes: https://github.com/ruimachado-orbit/axeng/releases/tag/v2.1.1
    CAVEATS
  end

  test do
    assert_match "axeng", shell_output("#{bin}/axeng --help")
  end
end
