# frozen_string_literal: true

class Axeng < Formula
  desc "Engineering Manager Accelerator — AI chief of staff for GitHub, Linear, calendar, and team"
  homepage "https://github.com/ruimachado-orbit/axeng"
  license "GPL-3.0"
  url "https://github.com/ruimachado-orbit/axeng.git", tag: "v2.2.0"
  version "2.2.0"
  head "https://github.com/ruimachado-orbit/axeng.git", branch: "main"

  depends_on "node"
  depends_on "python@3.12"
  depends_on "gh"

  def install
    # Install the entire repo to libexec
    libexec.install Dir["*"]

    # Create a Python virtual environment
    venv = libexec/"venv"
    system Formula["python@3.12"].opt_bin/"python3.12", "-m", "venv", venv

    # Install Python dependencies in the virtualenv
    system venv/"bin/pip", "install", "--upgrade", "pip"
    system venv/"bin/pip", "install", "-r", libexec/"requirements.txt"

    # Install Node.js dependencies for UI
    cd libexec/"ui/nextjs" do
      system "npm", "install"
    end

    # Create wrapper scripts
    (bin/"axeng").write <<~EOS
      #!/bin/bash
      export AXENG_HOME="#{var}/axeng"
      export PYTHONPATH="#{libexec}/src:$PYTHONPATH"
      export PATH="#{libexec}/ui/nextjs/node_modules/.bin:$PATH"

      # Ensure config directory exists
      mkdir -p "$AXENG_HOME"

      # If no arguments, show help
      if [ $# -eq 0 ]; then
        exec "#{venv}/bin/python3" "#{libexec}/bin/axeng-cli" --help
      fi

      # Run CLI with all arguments
      exec "#{venv}/bin/python3" "#{libexec}/bin/axeng-cli" "$@"
    EOS

    # Create axeng-dev wrapper (starts Next.js UI)
    (bin/"axeng-dev").write <<~EOS
      #!/bin/bash
      cd "#{libexec}/ui/nextjs"
      export AXENG_HOME="#{var}/axeng"
      export PYTHONPATH="#{libexec}/src:$PYTHONPATH"

      echo "🚀 Starting Axeng Next.js UI..."

      # Start API backend in background
      "#{venv}/bin/python3" api_server.py > /tmp/axeng-api.log 2>&1 &
      API_PID=$!

      # Start Next.js
      npm run dev

      # Kill API on exit
      kill $API_PID 2>/dev/null || true
    EOS

    chmod 0755, bin/"axeng"
    chmod 0755, bin/"axeng-dev"

    # Create var directory for user config
    (var/"axeng").mkpath

    # Copy example configs if they don't exist
    unless (var/"axeng/.env").exist?
      cp libexec/".env.example", var/"axeng/.env.example"
    end

    unless (var/"axeng/config.yaml").exist?
      cp libexec/"config/config.yaml.example", var/"axeng/config.yaml.example"
    end
  end

  def post_install
    ohai "🎉 Axeng v2.2.0 - Complete EM Platform!"
    puts ""
    puts "🆕 What's new in v2.2.0 - Strategic Features:"
    puts "  🎯 Sprint health & velocity tracking"
    puts "  📈 DORA metrics dashboard"
    puts "  📊 Automated weekly reports"
    puts "  ⏱️  Additional 10-15 hours saved per week!"
    puts ""
    puts "Quick start:"
    puts "  axeng configure    # Interactive wizard"
    puts "  axeng sprint       # Sprint health"
    puts "  axeng dora         # DORA metrics"
    puts "  axeng report --weekly  # Weekly summary"
    puts ""
    puts "Daily operations:"
    puts "  axeng standup      # Daily standup brief"
    puts "  axeng ooo          # Who's out today"
    puts "  axeng pr-health    # PR pipeline health"
    puts ""
    puts "Metrics & analytics:"
    puts "  axeng sprint --velocity    # Historical velocity"
    puts "  axeng dora --days 60       # DORA metrics"
    puts "  axeng report --weekly --send   # Send report"
    puts ""
    puts "Total time savings: 8+ hours per week!"
    puts ""
    puts "Configuration: #{var}/axeng/.env"
    puts "Release notes: https://github.com/ruimachado-orbit/axeng/releases/tag/v2.2.0"
  end

  def caveats
    <<~CAVEATS
      Axeng v2.2.0 - Complete EM Platform

      🆕 Strategic features in v2.2.0:
        🎯 Sprint health & velocity tracking
        📈 DORA metrics (4 key metrics)
        📊 Automated weekly reports
        ⏱️  Saves 8+ hours per week!

      Try the new commands:
        axeng sprint       # Sprint health analysis
        axeng dora         # DORA metrics dashboard
        axeng report --weekly  # Weekly summary

      Daily operations:
        axeng standup      # Daily standup
        axeng pr-health    # PR pipeline health
        axeng ooo          # Who's OOO

      All commands:
        axeng --help       # See full list

      Configuration:
        #{var}/axeng/.env          # Auto-generated by wizard
        #{var}/axeng/config.yaml   # Team/project settings

      Required API keys (get via interactive wizard):
        LINEAR_API_KEY      — linear.app/settings/api
        GITHUB_TOKEN        — github.com/settings/tokens
        LLM provider key    — OpenCode/Anthropic/OpenAI

      Release notes: https://github.com/ruimachado-orbit/axeng/releases/tag/v2.2.0
    CAVEATS
  end

  test do
    assert_match "axeng", shell_output("#{bin}/axeng --help")
  end
end
